---
- name: Send Mail with YAML Applications Files to Customers
  mail:
    host: "{{ sendmail_host }}"
    port: "{{ sendmail_port }}"
    from: "{{ sendmail_from }}"
    username: "{{ sendmail_username  }}"
    password: "{{sendmail_password }}"
    to: "{{ item.email }}"
    subject: "{{ sendmail_subject }}"
    body: "{{ sendmail_body }}" 
    attach: "{{ravello_fqdn_dir}}/{{ item.txt_app_file }} {{ shared_ssh_key}} {{ shared_ssh_key}}.ppk {{ sendmail_attach }}"
    charset: utf8
    secure: try
  with_items: "{{ sendmail_to }}"
  delegate_to: localhost
